name: Stats

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Da permisos de escritura para que el bot pueda subir el archivo stats.json creado
      contents: write

    steps:
      - name: checkout repositorio
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run script
        run: python ./stats.py

      - name: commit y push de cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "estadistica-Jonathan-paucar"
          commit_user_name: "Jonathan Paucar"
          commit_user_email: "jpaucar@estud.tesa.edu.ec"
          commit_author: "Jonathanpaucar<jpaucar@estud.tesa.edu.ec>"
