name: Stats

on:
 push:
   branches: [main]

jobs:
   build:
     runs-on: ubuntu-latest

  permissions:
   #Give the dafault GITHUB_TOKEN write permission to commit and push the 
   # added or changed files to the repository
  contents: write

steps:
- name: checkout repositorio
  use: actions/checkout@v6
  
- name: Setup python
  use: actions/setup-python@v6
  with:
      python-version: 3.13

  - name: Run script
    run: python./stats.py

  - name: commit y push de cambios
  use: stefanzweifel/git-auto-commit-action@v7
  with:
     commit_message: Update de estadisticas
     commit_user_name: melanievelasco12
     commit_user_email: mmvelasco@estud.tesa.edu.ec
     commit_author: melanie <mmvelasco@estud.tesa.edu.ec>
  

  

  
  
